version: '3'
tasks:
  test:
    cmds:
      - go test -v -count=1 ./...
  test-full:
    cmds:
      - go test -v -count=1 -race ./... -slow
  bench:
    cmds:
      - go test -v -bench=. -run=^$ ./...
