version: '3'
tasks:
  test:
    cmds:
      - go test -v -count=1 $(go list ./... | grep -v /bench)
  test-full:
    cmds:
      - go test -v -count=1 -race $(go list ./... | grep -v /bench) -slow
  bench:
    cmds:
      - go test -v -bench=. -run=^$ $(go list ./... | grep -v /bench)
